### ISSUE TITLE
make a new release

### ISSUE THREAD

**Issue by c-cube** [ocaml-toml/To.ml#56]
I can do it if @mackwic wants.

**Comment by mackwic** [comment]
By all means feel free ! 
Sadly, I won't be available for some weeks. :(

Things to do for a release:
- I've lost my opam credentials (new laptop. I didn't backuped the opam directory), so I think we have no other choice than make a new library ?
  - In this case, we need to share the credentials so that the risk is diminished... By mail ? A private gist shared by mail ?
- ❗️ We need to add you to the contributors in the opam file
- ❗️Make sure it compiles under the relevant Ocaml versions
  - CI is broken, we need to make it work again
    - ✅I've enabled the CI with travis
    - it should use the new build system and run the tests
    - ideally, it should push the doc on the gh-pages branches (which was the case before). It's easy with the ocaml-ci scripts we use
    - if needed, here's the doc: https://github.com/ocaml/ocaml-ci-scripts/blob/master/README-travis.md 
  - ❓what are the Ocaml version everyone is using now ?
- Make the release
  - let's make this release the v1.0.0 (changing the library name is a breaking change + we moved the structure anyway)
  - tag the version on master and push the tag
  - publish on opam (with the new name ?)
  - if we have a new name, we need to update the doc and communicate about it
    - can we ask opam to add a migration message ?

I am sorry to have more questions than guidance. And not much time to do the work

**Comment by c-cube** [comment]
I'm not sure what you mean by "opam credentials", actually. My normal mode of operation is to open a PR against opam-repository, and have some admin merge it, that's all?

**Comment by mackwic** [comment]
Oh ! great then 👍

Le dim. 12 août 2018 à 15:44, Simon Cruanes <notifications@github.com> a
écrit :

**Comment by c-cube** [comment]
https://github.com/ocaml/opam-repository/pull/12475
