### ISSUE TITLE
LGPL linking exception?

### ISSUE THREAD

**Issue by emberian** [ocaml-toml/To.ml#57]
Eg like this library http://calendar.forge.ocamlcore.org/ or camomile or murmur3

I was looking through all my opam deps and many of the libraries use LGPL "with Ocaml linking exception". Should this library?

**Comment by sagotch** [comment]
Can you explain what it would change?

**Comment by cmr** [comment]
my understanding is it tweaks the terms of the LGPL to enable this sort of scenarios: an open source software A is released that uses to.ml. someone modifies A, and distributes binaries without source (supposing A license allows this). without the linking exception the person distributing A must figure out how to distribute it so that it can be relinked with modified copies of to.ml. with the linking exception, they are free to do this without having to enable relinking.

**Comment by sagotch** [comment]
I will check this, but if it is true I am okay with that. I would agree to use a with MIT-like as well, but I just would like to understand what this linking exception actually is...

**Comment by zapashcanon** [comment]
Closing as I don't want to spend time contacting all the authors and asking them if they're OK with a license change. If someone is willing to do it, feel free to. :-)
